"""UYAP Evidence Ingestion Pipeline V1 — provenans-farkında veri-edinim alt sistemi.

Aşamalar: discovery → collection (tarayıcı-destekli / elle içe aktarma) → extraction →
same-asset reconciliation → rule-based completed-sale audit → human review → explicit
admission → mevcut UYAP kanıt şeması (``sold.structural``). Yapısal ekonometrik çekirdeği
DEĞİŞTİRMEZ; admisyon mevcut ``normalize_auction`` şemasına yazar ve UYAP P/Q moment tanımını
KORUR (pay = açık İhale Bedeli; ASLA Ödenmesi Gereken Bedel/depozito/hisse/mahsup/KDV).
"""

from __future__ import annotations

from . import admit, audit, bulk, collect, discovery, extract, models, pilot, pipeline, reconcile, review, store, udf
from .admit import INGESTION_BATCH, admit as admit_candidate, build_genuine_record, record_exclusion
from .bulk import (
    CATEGORY_TASINMAZ,
    MAX_WINDOW_DAYS,
    UyapBulkCollector,
    acquisition_state,
    classify_card_status,
    detect_session_expiration,
    extract_result_metadata,
    format_uyap_ui_date,
    generate_date_windows,
    is_sold_status,
    load_bulk_state,
    parse_result_cards,
    process_sold_auction,
    save_bulk_state,
    should_acquire,
    summarize_form_controls,
    summarize_result_structure,
    valid_result_pages,
    zero_results,
)
from .audit import audit_candidate
from .collect import (
    BROWSER_PREREQUISITES,
    BrowserCollector,
    card_document_list_control,
    classify_access_pattern,
    classify_action_semantic,
    classify_document_entry_path,
    classify_document_label,
    classify_document_list_container,
    classify_page_state,
    classify_view_access_pattern,
    classify_viewer_representation,
    classify_viewer_url,
    classify_viewer_outcome,
    classify_image_src_kind,
    classify_document_image_candidate,
    select_viewer_image_candidate,
    image_source_capture_supported,
    viewer_image_candidate_summary,
    decode_data_url,
    image_mime_to_extension,
    viewer_download_instruction_detected,
    extraction_supported_for,
    viewer_image_fingerprint,
    viewer_observation_signature,
    classify_viewer_ready_state,
    detect_cross_document_image_duplicates,
    classify_viewer_image_document_identity,
    resolve_viewer_image_identities,
    detect_document_container,
    detect_document_list,
    discover_document_links,
    document_container_kind_for_entry,
    document_list_semantic_transition,
    preopened_document_list_reusable,
    extract_document_rows_semantic,
    extract_panel_document_rows,
    file_identity_matches,
    find_target_record_card,
    has_document_list_control,
    import_artifact,
    normalize_file_identity,
    page_state_evidence,
    panel_has_documents,
    resolve_row_view_action,
    select_row_document_actions,
    select_target_page_index,
    select_unique_document_row,
    viewer_mime_hint,
    visible_document_types,
)
from .discovery import discover
from .extract import asset_descriptors, corroborate_native_document_type, classify_udf_document_type, extract_evidence
from .models import (
    ADMISSIBLE_COMPLETED_SALE,
    AUDIT_DECISIONS,
    DUPLICATE,
    EXCLUDED_NON_TERMINAL,
    MISSING_APPRAISAL,
    MISSING_AUCTION_PRICE,
    MISSING_TERMINAL_EVIDENCE,
    PENDING_REVIEW,
    RECONCILIATION_FAILED,
    AuditResult,
    ExtractedEvidence,
    ReconciliationResult,
    SourceArtifact,
    parse_tl_amount,
)
from .pipeline import run_audit, run_extract, status_summary
from .pilot import (
    KNOWN_TRUTH,
    MODE_LIVE,
    MODE_OFFLINE,
    PILOT_NAME,
    compare_to_truth,
    genuine_fingerprint,
    run_pilot,
    verify_pilot,
)
from .reconcile import reconcile
from .review import needs_review, review_item, review_queue
from .udf import MAX_UDF_DECOMPRESSED_BYTES, extract_udf_source_text, native_udf_supported

__all__ = [
    "admit",
    "audit",
    "collect",
    "discovery",
    "extract",
    "models",
    "pipeline",
    "reconcile",
    "review",
    "store",
    # işlevler
    "discover",
    "import_artifact",
    "extract_evidence",
    "run_extract",
    "reconcile",
    "audit_candidate",
    "run_audit",
    "review_queue",
    "review_item",
    "needs_review",
    "admit_candidate",
    "build_genuine_record",
    "record_exclusion",
    "status_summary",
    "parse_tl_amount",
    "BrowserCollector",
    "BROWSER_PREREQUISITES",
    "discover_document_links",
    "classify_document_label",
    "has_document_list_control",
    "select_row_document_actions",
    "classify_access_pattern",
    "panel_has_documents",
    "extract_panel_document_rows",
    "extract_document_rows_semantic",
    "detect_document_list",
    "detect_document_container",
    "visible_document_types",
    "document_list_semantic_transition",
    "document_container_kind_for_entry",
    "preopened_document_list_reusable",
    "resolve_row_view_action",
    "classify_action_semantic",
    "classify_document_list_container",
    "classify_viewer_url",
    "viewer_mime_hint",
    "classify_viewer_representation",
    "classify_view_access_pattern",
    "classify_viewer_outcome",
    "classify_image_src_kind",
    "classify_document_image_candidate",
    "select_viewer_image_candidate",
    "image_source_capture_supported",
    "viewer_image_candidate_summary",
    "decode_data_url",
    "image_mime_to_extension",
    "viewer_download_instruction_detected",
    "extraction_supported_for",
    "viewer_image_fingerprint",
    "viewer_observation_signature",
    "classify_viewer_ready_state",
    "detect_cross_document_image_duplicates",
    "classify_viewer_image_document_identity",
    "resolve_viewer_image_identities",
    "classify_page_state",
    "page_state_evidence",
    "select_target_page_index",
    "normalize_file_identity",
    "file_identity_matches",
    "find_target_record_card",
    "card_document_list_control",
    "classify_document_entry_path",
    "asset_descriptors",
    "INGESTION_BATCH",
    # native UDF (Fix 12)
    "udf",
    "extract_udf_source_text",
    "native_udf_supported",
    "MAX_UDF_DECOMPRESSED_BYTES",
    "classify_udf_document_type",
    "corroborate_native_document_type",
    "select_unique_document_row",
    # bulk discovery + iteration (Geçmiş İlanlar; reuses the single-auction path)
    "bulk",
    "UyapBulkCollector",
    "CATEGORY_TASINMAZ",
    "MAX_WINDOW_DAYS",
    "generate_date_windows",
    "format_uyap_ui_date",
    "valid_result_pages",
    "is_sold_status",
    "classify_card_status",
    "extract_result_metadata",
    "zero_results",
    "detect_session_expiration",
    "parse_result_cards",
    "acquisition_state",
    "should_acquire",
    "process_sold_auction",
    "summarize_form_controls",
    "summarize_result_structure",
    "load_bulk_state",
    "save_bulk_state",
    # pilot (live browser verification)
    "pilot",
    "run_pilot",
    "verify_pilot",
    "compare_to_truth",
    "genuine_fingerprint",
    "KNOWN_TRUTH",
    "PILOT_NAME",
    "MODE_LIVE",
    "MODE_OFFLINE",
    # modeller / sözlük
    "SourceArtifact",
    "ExtractedEvidence",
    "ReconciliationResult",
    "AuditResult",
    "AUDIT_DECISIONS",
    "ADMISSIBLE_COMPLETED_SALE",
    "EXCLUDED_NON_TERMINAL",
    "PENDING_REVIEW",
    "DUPLICATE",
    "RECONCILIATION_FAILED",
    "MISSING_APPRAISAL",
    "MISSING_AUCTION_PRICE",
    "MISSING_TERMINAL_EVIDENCE",
]
